### ISSUE TITLE
Benutzer bearbeiten: Vorauswahl der Sprache inkorrekt

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/neg#125]
im Backend unter Administration => Benutzer verw.:

Es gibt einige Benutzer bei denen in der Spalte "Sprache" der Wert "gb" (für Englisch) eingetragen ist.
Öffnet man aber den Benutzer über die Schaltfläche "ändern", wird in der Liste trotzdem "Deutsch" angezeigt, d.h. wenn man nicht darauf achtet und speichert dann wird versehentlich die Sprache geändert. Beim Öffnen der Maske sollte die bereits hinterlegte Sprache korrekt vorausgewählt werden.

**Comment by juro-ub** [comment]
Ich habe für dieses Issue einen PR erstellt.
Mit Hilfe des Attributes "selected" wird nun die hinterlegte Sprache vorausgewählt.
