### ISSUE TITLE
Problem Alignment Tool: Too many rows in source or target table

### ISSUE THREAD

**Issue by juro-ub** [ubtue/neg#132]
The following picture shows the mapping of the table dmp.konvent to neg.selektion_konvent.

On the left side you see the column "source". This column represents all rows from the source table dmp.konvent.

The column "target" contains a select field. This select field contains all rows from the target table.

![image](https://github.com/ubtue/neg/assets/104774773/8a75906d-1e00-4c36-8f35-7066c96434e9)

The problem appears when the target- or source table have more than 1000 rows. Then it might happend that the browser will crash. Because the select field and the column source containing to many values

**Comment by mtrojan-ub** [comment]
Maybe we need a special kind of AJAX-based select element, where the user can only see a subset and also has a search mechanism?

Here's just a first jQuery-based dropdown i found when googling for a couple of minutes:
https://blog.quickadminpanel.com/select2-dropdowns-with-big-data-load-options-via-ajax-laravel/

Maybe there's a better one?
