### ISSUE TITLE
Namenkommentar: Fehler beim Anklicken im Backend

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/neg#16]
http://ub45.v264.uni-tuebingen.de/neg/namenkommentar.jsp?ID=1

![grafik](https://user-images.githubusercontent.com/26873381/175292605-6063a864-f8eb-4853-9013-f9f9fc31d5ad.png)

![grafik](https://user-images.githubusercontent.com/26873381/175292708-22d9a76f-79cd-4ad1-ac0d-348dca5183e1.png)

**Comment by mtrojan-ub** [comment]
Auf Testserver behoben

**Comment by rnaiser** [comment]
ja bei mir geht auch alles wenn ich iso_049... .doc dort speichere
