### ISSUE TITLE
NeG: Hinweis auf Umstellung auf NPPM

### ISSUE THREAD

**Issue by ChristophHaack** [ubtue/neg#192]
Lieber Herr Trojan (und Kollegen),

ich habe eine Bitte zu NeG: Derzeit ist NPPM ja noch nicht öffentlich zugänglich/findbar, die NeG-homepage aber schon. Allerdings wird die website nicht mehr aktualisiert und sie ist technisch auch schon in die Jahre gekommen. 
Deshalb wäre es schön, wenn es bei Nutzung der NeG-homepage einen entsprechenden Hinweis gäbe. Einen Text würde ich verfassen, aber könnten Sie das technisch umsetzen? – Die NeG-Seite ist mit Drupal gestaltet, ich weiß nicht, ob Sie dort leicht ein Pop-up o.ä. einfügen könnten (ich kann zwar Inhalte hinzufügen, aber für ein Pop-up u.ä. wäre ich wahrscheinlich ein paar Tage lang mit nichts anderem beschäftigt, weil ich im Moment nicht weiß, wie das geht). – Oder könnten Sie alternativ z.B. eine Seite zwischenschalten, die einen Hinweis zeigt und auf der man dann zu NeG „weiter“ gehen kann? – Vll. gibt es ja auch noch eine andere Lösung?

Freundliche Grüße
Christoph Haack

**Comment by mtrojan-ub** [comment]
Lieber Herr Haack,

meinen Sie mit NeG-Homepage bzw. Drupal folgende Seite?
www.neg.uni-tuebingen.de

Diese wird nicht bei uns an der UB betrieben, daher haben wir darauf auch keinen Zugriff. 
Ggf können Sie das direkt mit @ThoFischer besprechen?

Viele Grüße
Mario Trojan

PS: Wenn ich es richtig verstehe soll die Drupal Seite ohnehin abgelöst werden sobald wir Anfang 2025 das Web-Frontend überarbeiten.

**Comment by ChristophHaack** [comment]
Es tut mir leid, dass ich so spät antworte! - Die letzten 3 Wochen war ich weitgehend mit Corona in der Familie beschäftigt, sodass ich erst jetzt zu einer Antwort komme.  

Die betreffende website hätte ich natürlich angeben sollen, ja, es handelt sich um [www.neg.uni-tuebingen.de](http://www.neg.uni-tuebingen.de/). 

Mir war ehrlich gesagt nicht klar, von wem die Seite verwaltet wird. Des eine offizielle "uni-tuebingen.de"-Seite ist hatte ich angenommen, sie wäre mit der Datenbank auch an die UB übertragen worden. Wenn das nicht so ist, müsste sie wahrscheinlich noch in irgendeiner Form beim alten eScience-Center sein. Es wäre dann aber gut, sie auch an die jetzige technische Betreeung von NPPM zu übergeben! 

Können Sie mir sagen, was ich dafür tun muss? Zuerst mal müsste ich herausfinden, wo die Seite derzeit liegt und theoretisch verwaltet wird.

Und noch einmal direkt zum ursprünglichen Anliegen: Besprochen hatte ich die Frage mit Steffen Patzold, da www.neg.uni-tuebingen.de bisher von mir inhaltlich betreut wurde. Thorsten hat soweit ich weiß gar keinen Zugriff. Jetzt ginge es im Grunde darum, dass Nutzer beim Zugriff auf die NeG-Datenbank einen Hinweis darauf bekommen, dass NeG Teil von NPPM wird. 

Man könnte auch die jetzige homepage abschalten und einen entsprechenden Hinweis (u. ggf. die noch relevanten Informationen von der alten homepage) in irgendeiner Form der Datenbank vorschalten - wie das technisch umgesetzt ist, spielt aus inhaltlich-fachlicher Perspektive eigentlich keine Rolle.

Viele Grüße
Christoph Haack

**Comment by mtrojan-ub** [comment]
Lieber Herr Haack,

in Absprache mit Hr. Patzold beim gestrigen Projektmeeting müssten die Anpassungen an der alten Drupal Website aktuell noch über Fr. Grabowsky laufen. Hr. Patzold möchte hier auf dem kurzen Dienstweg auf Sie + Fr. Grabowsky zugehen.

Viele Grüße
Mario Trojan

**Comment by ChristophHaack** [comment]
Lieber Herr Trojan,
vielen Dank für die Antwort, ich werde das dann klären.
Viele Grüße
Christoph Haack
