### ISSUE TITLE
Admin funktion für nicht Admins zugänglich - soll das so sein !?

### ISSUE THREAD

**Issue by rnaiser** [ubtue/neg#195]
Bislang ist es im Backend möglich, auch als nicht-administrative Person, im Bereich 'Ethnie/Areal' im Feld 'Areal' neue Einträge unter 'Neuer Eintrag erstellen' hinzuzufügen. Diese Funktion ist normalerweise über die Administration zugänglich, die jedoch nicht in der Seitenleiste sichtbar ist, da es sich um ein Nicht-Admin-Konto handelt.
Meine Frage ist, ob das so beabsichtigt ist oder ob das Pluszeichen nur angezeigt werden soll, wenn der Benutzer Administratorrechte hat.

![image](https://github.com/ubtue/neg/assets/105979344/4dfdf62a-0cc2-4b27-8dd4-f9f20acca774)

![image](https://github.com/ubtue/neg/assets/105979344/b889b55f-abc6-404f-a24a-679850fd6f6d)

![image](https://github.com/ubtue/neg/assets/105979344/6ed2ead1-9cd0-428d-96a1-91252049441a)

**Comment by rnaiser** [comment]
@ThoFischer please take a look

**Comment by ThoFischer** [comment]
Lieber Herr Naiser,

vielen Dank für den Hinweis.
Dann sollten wir es so handhaben, wie es normalerweise gemacht wurde.
Wenn Sie sagen, dass es "bislang  im Backend möglich ist , auch als  
nicht-administrative Person, im Bereich 'Ethnie/Areal' im Feld 'Areal'  
neue Einträge unter 'Neuer Eintrag erstellen' hinzuzufügen", habe ich  
mich gefragt, wie dies etwa bei Amt/Stand oder Funktion geregelt ist?
Wir haben ja durchaus Fälle, wo Nutzer neue Namen eingeben müssen und  
dann eventuell ja auch die Felder 'Ethnie/Areal' oder "Amt/Weihe etc."  
füllen müssen. Wäre dies ohne die Admin-Rechte noch möglich?

Herzliche Grüße aus Duisburg

Thorsten Fischer
Zitat von rnaiser ***@***.***>:

**Comment by rnaiser** [comment]
Hallo Herr Fischer,
Bei Amt/Stand/Weihe (Person) ist es so das keiner weder Admin noch nicht Admin direkt im Reiter Amt/Stand/Weihe ein neues Feld anlegen kann,
![image](https://github.com/ubtue/neg/assets/105979344/cc5ba9f6-3ee2-4afc-9e5e-aa47b7480f3a)

 sondern nur Admins , die es aber an der Linken seite im menue Administration 

![image](https://github.com/ubtue/neg/assets/105979344/f9e595b9-ae93-4f0e-a9e4-4a792eae9457)

im Tab Auswahlfelder dann selektion_amtweihe udn selektion_stand dann bearbeiten 

![image](https://github.com/ubtue/neg/assets/105979344/84dde815-5a1c-4def-9bda-715267e64d9d)

und es dann dort ein neues feld Anlegen können

![image](https://github.com/ubtue/neg/assets/105979344/9bf3aac1-6aaa-4ac4-97d7-4387d6b57217)

**Comment by rnaiser** [comment]
In Textzeugen kann bei 

Schriftheimat und Biblio.heimat nicht Admins und Admins auch neue Felder/Eintrag anlegen und es gibt soweit ich sehen keine möglichkeit bei Administration das zu tun 
![image](https://github.com/ubtue/neg/assets/105979344/cc8e01cf-dd41-497a-9bea-c7997394dbf3)

wir können sonst auch das nächste mal ganz genau in dem kommenden Workshop sonst besprächen ob das dann z.b auch in der Administration zugänglich sein soll

**Comment by rnaiser** [comment]
auch kann ein nicht Admin das bei Editionen und dann Tab Editoren auch neue Felder/Einträge  anlegen. 
Sie schrieben: Wir haben ja durchaus Fälle, wo Nutzer neue Namen eingeben müssen und
dann eventuell ja auch die Felder 'Ethnie/Areal' oder "Amt/Weihe etc."
füllen müssen. Wäre dies ohne die Admin-Rechte noch möglich?

bis jetzt können die nicht Admin das so weit tun. also kann man das so lassen wie es bereits war ?

gruß Ryan

**Comment by ChristophHaack** [comment]
Ich sehe die Frage gerade (erst) und weiß nicht, ob meine Antwort jetzt noch hilft, aber: Die genannten Möglichkeiten (Anlegen eines neuen Areals + Anlegen neuer Editionen) sind auch für nicht-Admin-Nutzer verfügbar, weil es so oft vorkommt, dass ein Bearbeiter diese Dinge neu anlegen muss. Hier war es sinnvoll, dass jeder Bearbeiter diese Einträge hinzufügen kann.

**Comment by ChristophHaack** [comment]
Die anderen Einträge - besonders "Ethnie", aber auch "Amt" usw. - sollten nur von den Admins vorgenommen werden, weil sie zentrale Kategorien des Projekts abbilden. Hier sollte also nicht jeder Bearbeiter o. Nutzer Dinge hinzufügen können.
Im FAZIT heißt das jetzt natürlich nur, dass - wie Thorsten schon gesagt hat -  die Möglichkeiten so bleiben sollten, wie sie sind. Aber das noch als Erklärung.

Viele Grüße
Christoph
